sudo: false
language: node_js
node_js:
- 16
env:
- TSI2_LING7='build'
#- TSI2_LING7='test'
- TSI2_LING7='check'
branches:
  only:
  - master
  # - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
script:
- echo npm run $TSI2_LING7
- npm run $TSI2_LING7
deploy:
  # - provider: npm
  #   skip_cleanup: true
  #   email: a8568730@gmail.com
  #   api_key:
  #     secure: BZDiOrzQiWUo8u+B1ux5w7QjWzJBe3E7MuFt0CJseuSJilyf/OIX4M09kOcyheSBZLOI8o21+UTPquK9A6qqLfiA5rHYCXwRF4zGcawBr8tQYHfDeZbFFqfWAvlgQso0DmrvN3CT0KgxiHCG6hEQ2WNEwvSnXMlaJTHwcom/F7/C9Xl9POKoG2FzYetQ7XYKryZsQquSc9NymFvo+erYS8AXf0CM1TmfbThzEuVoh/N6APOWTwj0rVW1qJ8prlE08tiAqkMAUG7Bg3Op+/He8fTTY7wQvQmdzYnydnUkPpziTzXwEUjHHyJWRZ+LbuAG/v6/eEyv9Pv4cv7Mr7p+VU3ABKOznZ0ZRTGpl6i40MwFYQ62KRnqyAnZMc70eILcnGIpoMx3ZCti7EggB4lBckJU7XtCC94U2TZ+fevnuPzh47z0C8xLxknIPO6+pb9oEmfVHTyM3CJ5JEzI2jbI60CcsTnietVBO0p6ZFFm2dyLs6qaxodmSzwWwDLIdDD/uSXoG1wUFB697F71v6yJnuyhdd2NKZK1huKBONuThrYW1sRGnP9WKvy/aknP/81mhy1mKtaQuM4Ii2L9tHlux8pe1MlBRw/ACFc/oIHUup031J21Ok8/ZH8zw2S/0EfQ902TnMQibbPSIloz5BHzQLCFRrSSlG7E//ZJc0A4cmE=
  #   on:
  #     tags: true
  #     repo: i3thuan5/TenSu-Demo
  #     condition: $TSI2_LING7 = build
  - provider: pages
    fqdn: tensu.ithuan.tw
    skip_cleanup: true
    local_dir: build/
    github_token: ${GITHUB_TOKEN}
    on:
      branch: master
      condition: $TSI2_LING7 = build
